server {
    server_name docs.sfucsss.org;
    http2 on;
    listen 80;

    root /var/www/html/docs;

    access_log /var/www/logs/csss-site-docs/nginx-access.log;
    error_log /var/www/logs/csss-site-docs/nginx-error.log;

    set $auth_required_role "exec";
    include snippets/auth-guard.conf;
    include snippets/errors.conf;

    location /_astro/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        auth_request /_auth;
        error_page 401 = @login;

        try_files $uri $uri/ /index.html =404;
    }
}
