# The configuration for the event domains:
#   - Frosh: frosh.sfucsss.org
#   - Fall Hacks: fall-hacks.sfucsss.org
#   - Tech Fair: tech-fair.sfucsss.org
#   - Mountain Madness: madness.sfucsss.org

map $host $event_root {
    default /var/www/html/__unknown_event__;
    fall-hacks.sfucsss.org /var/www/html/fall-hacks;
    frosh.sfucsss.org /var/www/html/frosh;
    madness.sfucsss.org /var/www/html/madness;
    tech-fair.sfucsss.org /var/www/html/tech-fair;
}

server {
    http2 on;
    listen 80;

    server_name
        fall-hacks.sfucsss.org
        frosh.sfucsss.org
        madness.sfucsss.org
        tech-fair.sfucsss.org;

    root $event_root;

    # Legacy shared assets
    location /static/ {
        alias /var/www/html/static/;
        try_files $uri $uri/ =404;
    }

    location ~ "^/(?<year>\d{4})(/.*)?$" {
        # Don't index sites for different years.
        add_header X-Robots-Tag "noindex, nofollow" always;
        try_files $uri $uri/ $uri.html $year/index.html =404;
    }

    location / {
        root $event_root/latest;
        try_files $uri $uri/ /index.html =404;
        add_header Cache-Control "no-cache";

        location /assets/ {
            try_files $uri =404;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}

