location = /_auth {
    internal;

    proxy_pass http://backend/auth/verify;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Cookie $http_cookie;

    proxy_set_header X-Required-Role $auth_required_role;
}

location @login {
    rewrite ^ /auth/login break;

    proxy_set_header X-Original-URL $scheme://$host$request_uri;
    proxy_set_header Host sfucsss.org;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://backend;
}

