location = /_auth {
    internal;

    proxy_pass http://backend/auth/verify;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Cookie $http_cookie;
}

location @login {
    return 302 https://sfucsss.org/auth/login;
}

