# Internal means the public can't reach these.
location = /_errors/403.html {
    internal;
    alias /var/www/html/errors/403.html;
}

location = /_errors/404.html {
    internal;
    alias /var/www/html/errors/404.html;
}

location = /_errors/500.html {
    internal;
    alias /var/www/html/errors/500.html;
}

location = /_errors/502.html {
    internal;
    alias /var/www/html/errors/502.html;
}

# Required to serve all the content in `/var/www/html/errors`
location ^~ /_error-assets/ {
    alias /var/www/html/errors/assets;
}
