error_page 403 /_errors/403.html;
error_page 404 /_errors/404.html;
error_page 500 /_errors/500.html;
error_page 502 /_errors/502.html;

location = /_errors/403.html {
  internal;
  alias /var/www/html/errors/403.html;
}

location = /_errors/404.html {
  internal;
  alias /var/www/html/errors/404.html;
}

location = /_errors/500.html {
  internal;
  alias /var/www/html/errors/500.html;
}

location = /_errors/502.html {
  internal;
  alias /var/www/html/errors/502.html;
}
